### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by chriskrycho** [dawnlabs/carbon#203] opened 2018-02-05 13:18 UTC
## Expected Behavior

The editor functionality should work in iOS Safari.

## Actual Behavior

There is no visible cursor, and the invisible cursor that is placed on the page does not work correctly, and clicking the Tweet and Save buttons simply does nothing.

**Comment by mfix22** [comment] 2018-02-05 16:13
Duplicate of #28. Closing.

**Closed by mfix22** 2018-02-05 16:13 UTC
