### ISSUE TITLE
Feature Request: Window button position should be configurable

### ISSUE THREAD

**Issue by OttoRobotto** [dawnlabs/carbon#320] opened 2018-04-09 15:29 UTC
## Expected Behavior
There should be an option to place the window buttons on the top right corner of the window instead of the top left

## Actual Behavior
Window buttons appear strange at the top left of the window for non mac users

**Comment by mfix22** [comment] 2018-04-09 23:57
Hey @OttoRobotto would you say this is duplicate of #3 or no? Just wondering if this issue is because you want a Windows theme, or a separate option for it to not be in the top-left 😄 

If you meant the former, i can go ahead and close this issue

**Comment by OttoRobotto** [comment] 2018-04-10 08:27
Hey @mfix22, I quite like the current available themes but would really just like to be able to place the window control buttons at the top right of the window. If I have the time I'll attempt to implement this myself.

**Comment by mfix22** [comment] 2018-06-24 18:53
Cool! We should implement it in the same way as the other window options though, so I am going to close this as a duplicate of #25. Please feel free to send a PR and we will review 😄

**Closed by mfix22** 2018-06-24 18:53 UTC
Labels: enhancement
