### ISSUE TITLE
Unusable on an iPad

### ISSUE THREAD

**Issue by Frizlab** [dawnlabs/carbon#677] opened 2019-02-17 20:11 UTC
### Expected Behavior
Using the keyboard on the iPad should work correctly, like with any text view on the web.

### Actual Behavior
The space bar does not enter a space, but scrolls the webpage instead, there is no selection possible, nor can we see the carret where the text will be inputted.
<details>
  <summary>Browser: </summary>
  
Safari on iOS 12.1.4, on iPad Pro 12.9”
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment] 2019-02-17 20:20
This is probably the same issue as https://github.com/dawnlabs/carbon/issues/506

**Comment by Frizlab** [comment] 2019-02-17 20:24
Seems to be, indeed. Do you want me to close this one? Or you can do it 🤷‍♂️

**Comment by mfix22** [comment] 2019-02-17 20:29
@Frizlab I'll close it, thank you for posting 👍 This is a fundamental issue with CodeMirror, the editor we use. Please track the other issue for update.

**Comment by mfix22** [comment] 2019-02-17 20:29
Duplicate of #506

**Closed** 2019-02-17 20:29 UTC
Labels: duplicate
