### ISSUE TITLE
Does not accept any files or text in Palemoon browser

### ISSUE THREAD

**Issue by tytower** [dawnlabs/carbon#245] opened 2018-02-18 20:43 UTC
## Actual Behavior

**Comment by mfix22** [comment] 2018-02-18 21:25
Duplicate of #28

**Closed by mfix22** 2018-02-18 21:25 UTC

**Comment by tytower** [comment] 2018-03-24 19:45
Running through closing issues all over the place but not actually fixing anything . What the heck do you think you are doing ?
The questions are placed looking for fixes not closed stamps . Did they give you that stamp in Kindergarten?

**Comment by tytower** [comment] 2018-03-24 19:46
"Does not accept any files or text in Palemoon browser"

**Comment by mfix22** [comment] 2018-03-24 20:58
Hey @tytower thanks for you comments. We haven't released our fix for Safari support, but I will test if on Palemoon and try and mimick that support there.
