### ISSUE TITLE
Suggestions: about config and theme

### ISSUE THREAD

**Issue by mdluo** [dawnlabs/carbon#303] opened 2018-03-31 05:17 UTC
## Expected Behavior
- The watermark option to be in the url params.
- Save the image with filename same as the title or a filename containing datetime to avoid a series of 'carbon.png, carbon (1).png, carbon (2).png...' when saving to the same folder.
- The exported png filename to end with `@2x.png` when the 'Export size' is set to 2x.
- The [Atom One color scheme](https://github.com/atom/one-dark-syntax) is great and popular and could be taken into consideration.

## Actual Behavior

**Comment by mfix22** [comment] 2018-03-31 20:10
> The watermark option to be in the url params.

53b8965b7928aa14b01f5544428112a96ad39188 fixes this (:
> Save the image with filename same as the title or a filename containing datetime to avoid a series of 'carbon.png, carbon (1).png, carbon (2).png...' when saving to the same folder.

Duplicate of https://github.com/dawnlabs/carbon/issues/277. We have decided that we are going to let browsers handle how saving/downloading renaming is handled.

> The exported png filename to end with @2x.png when the 'Export size' is set to 2x. 

As of right now, we are going to let all renaming happen in the "Save As" dialog. Otherwise the file names could get crazy as more properties are added to them.

> The Atom One color scheme is great and popular and could be taken into consideration.

The Carbon core theme is willing to accept PRs to add themes or languages, but we will not be implementing them ourselves (see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for details). If you want to add this theme, please submit us a PR 😄

**Closed by mfix22** 2018-03-31 20:10 UTC
