### ISSUE TITLE
Text background color

### ISSUE THREAD

**Issue by skarif2** [dawnlabs/carbon#618] opened 2019-01-05 05:42 UTC
Is there any way to change the background color of the text. I was expecting a green background color for the text "HTTP/1.1" but there wasn't any.

### Expected Behavior
![screenshot 2019-01-05 at 11 30 56 am](https://user-images.githubusercontent.com/5141132/50720792-143f7d00-10de-11e9-9d27-143236555553.png)

### Actual Behavior
![carbon](https://user-images.githubusercontent.com/5141132/50720795-1d304e80-10de-11e9-904d-ee87202cda3f.png)

**Comment by mfix22** [comment] 2019-01-08 06:11
Hey @skarif2 thanks for posting this issue. Carbon is actually behaving correctly in this case, since it just reads and colorizes your text based on a specific language. However there is an open issue (#548) to support this, which allows you to color specific parts of the text a specific color (or background color).

Going to close this issue as a duplicate of #548

**Closed by mfix22** 2019-01-08 06:11 UTC
