### ISSUE TITLE
Feature request: split screen/side-by-side editor

### ISSUE THREAD

**Issue by mddanishansari** [dawnlabs/carbon#403] opened 2018-06-21 06:14 UTC
It would be really nice if we can have the feature of split screen(side-by-side or top-bottom) like most of the modern editors do.

It can be useful when you have to compare 2 codes, show difference, good code/bad code etc

I have absolutely no idea how this can be done. Otherwise I would have created a PR

**Comment by mfix22** [comment] 2018-06-23 18:30
Hi @mddanishansari thanks for opening an issue. This is a duplicate of https://github.com/dawnlabs/carbon/issues/337 which we are not supporting as of now. We will reopen #337 if we decide to go that direction 😄

**Closed by mfix22** 2018-06-23 18:30 UTC

**Comment by mddanishansari** [comment] 2018-06-23 18:32
Ok

**Comment by kievsash** [comment] 2019-09-26 05:33
+1
Example of possible usage:
https://twitter.com/thekiba_io/status/1136908291366408192?s=20
