### ISSUE TITLE
Suggestion: Only syntax highlight range

### ISSUE THREAD

**Issue by Relequestual** [dawnlabs/carbon#824] opened 2019-07-19 14:37 UTC
It's not uncommon to see presentations or code images where most of the code is de-coloured / not syntax highlighted, and only a specific range or set of ranges are highlighted.

I've worked out a possible solution.

CodeMirror supports marking a range of text with a class.
https://codemirror.net/doc/manual.html#api_marker

The CSS can then be added to make ALL text grey (or a themes comment colour?), only keeping the syntax highlighting for a specific section.

The CSS would look something like...
```
:not(.colourise) > span {
    color: gray !important;
}
```

Applying the class of `colourise` to a presentation span, then results in the attached screenshot result.
![Screen Shot 2019-07-19 at 15 32 10](https://user-images.githubusercontent.com/731158/61543305-1b572880-aa3b-11e9-8909-60d53a8282dd.png)

**Comment by Relequestual** [comment] 2019-07-19 14:45
OR, actually, a simpler solution might be to invert the user entered range, add a class of `cm-comment` using the codemirror API, which then handles which colour to pick.

**Comment by mfix22** [comment] 2019-07-19 17:29
This is a lesser known feature, but we already have support for highlighting/selecting lines. You have to turn on "Line numbers" in the settings, but then by clicking on the line numbers you can (de)select certain lines to highlight them. If you click, and then Shift-click another line, that will batch select a group of lines. 

We also want to use opacity in order to ensure that deselection always looks good, no matter what the theme is.

**Comment by mfix22** [comment] 2019-07-19 17:30
@Relequestual your comment about https://codemirror.net/doc/manual.html#api_marker is going to be _super_ useful for #548 and #806 though 👍

**Comment by mfix22** [comment] 2019-07-19 17:33
As for applying styles to a range, we will cover that as part of the other issues :+1: Duplicate of #548/#806

**Closed** 2019-07-20 17:33 UTC
Labels: duplicate

**Comment by Relequestual** [comment] 2019-07-22 08:08
Huh, well I hadn't noticed you could already do line by line selection. This is pretty useful, thanks!

Looks like #806 has the same use case as me.

Now to file an issue on the cli repo!

**Comment by Relequestual** [comment] 2019-07-22 08:29
@mfix22 Hum. Given it looks like the cli tool `carbon-now-cli` works by using URL query string.

Is there any way "lines selected" could be added to the query string?

**Comment by mfix22** [comment] 2019-07-24 20:41
@Relequestual sure! We probably have to refactor how the line selection state is handled first. Would you want to work on this? Otherwise I will get to it when there is time 🙂

**Comment by Relequestual** [comment] 2019-08-19 11:39
I wish I had time @mfix22! Appreciate you working on this!
