### ISSUE TITLE
Image doesn't download on Safari 11

### ISSUE THREAD

**Issue by efgm1024** [dawnlabs/carbon#119] opened 2017-10-22 21:39 UTC
![screen shot 2017-10-22 at 3 35 15 pm](https://user-images.githubusercontent.com/1943459/31866579-f477777e-b73e-11e7-85ed-c5112beb83c9.png)

## Expected Behavior
Download image on Safari
## Actual Behavior
Image won't download because of error `Unhandled Promise Rejection`
Safari Version 
![screen shot 2017-10-22 at 3 36 13 pm](https://user-images.githubusercontent.com/1943459/31866590-30d6bda6-b73f-11e7-9bc9-75048129bfb9.png)

**Comment by mfix22** [comment] 2017-10-23 05:15
Duplicate of #28
Thanks for filing the issue! It is our highest priority. Closing.

**Closed by mfix22** 2017-10-23 05:15 UTC
