### ISSUE TITLE
Doesn't work on mobile at all…

### ISSUE THREAD

**Issue by NSExceptional** [dawnlabs/carbon#573] opened 2018-11-12 08:29 UTC
Did you guys even test it there?

- Cannot select or otherwise manipulate text other than typing
- Cannot insert spaces

**Comment by photonstorm** [comment] 2018-11-12 10:05
![image](https://user-images.githubusercontent.com/164476/48340401-70e46580-e662-11e8-9672-0c2b987979c5.png)

**Comment by mfix22** [comment] 2018-11-15 00:13
Duplicate of #506

This is a priority of ours. However there are many mobile limitations caused by `CodeMirror` 

If you have suggestions, please raise them on #506

**Closed by mfix22** 2018-11-15 00:13 UTC

**Comment by NSExceptional** [comment] 2018-11-16 08:18
Thanks!
