### ISSUE TITLE
Tweet button not working

### ISSUE THREAD

**Issue by JiDai** [dawnlabs/carbon#197] opened 2018-02-04 09:37 UTC
Hi,

I am on last version of safari.

## Expected Behavior
The 'tweet  image'  button open a tweet

## Actual Behavior
The 'tweet  image' button do nothing (after a short loading state)
I got an error in JS console

**Comment by mfix22** [comment] 2018-02-04 19:12
This is a duplicate of #28. Unfortunately our app does not work on Safari yet. It is our highest priority and we are working on it.

Closing.

**Closed by mfix22** 2018-02-04 19:12 UTC

**Comment by JiDai** [comment] 2018-02-05 09:54
Ok, thanks
