### ISSUE TITLE
Chinese word

### ISSUE THREAD

**Issue by ChendayUP** [dawnlabs/carbon#709] opened 2019-03-21 03:45 UTC
**Describe the bug**
Chinese word show Square

**Screenshots**
![carbon](https://user-images.githubusercontent.com/20022523/54732524-36ba4000-4bcf-11e9-9c9a-1f11f1d57346.png)

**Info (please complete the following information):**
 - Browser [e.g. chrome, safari]: 
 - 
<details>
if [ -f ./oclint_result.html ]; then echo '-----分析完毕-----'
else echo "-----分析失败-----"; fi
</details>

**Comment by ChendayUP** [comment] 2019-03-21 03:46
![carbon](https://user-images.githubusercontent.com/20022523/54732462-e0e59800-4bce-11e9-92e1-ca5446f8812a.png)

**Comment by mfix22** [comment] 2019-03-21 16:37
Hello! Does this occur in both Chrome and Safari? Or only Safari...

**Comment by mfix22** [comment] 2019-03-22 00:46
@ChendayUP this is a duplicate of #439. I have updated that issue to make sure Chinese characters get fixed as well for Safari

**Closed** 2019-03-23 00:46 UTC
Labels: duplicate
